
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 8;
  public static final int Parentesis_c = 22;
  public static final int Numero_entero = 27;
  public static final int Parentesis_a = 21;
  public static final int Suma = 13;
  public static final int Leer = 29;
  public static final int Op_booleano = 20;
  public static final int Entero = 5;
  public static final int ERROR = 31;
  public static final int Mientras = 10;
  public static final int Para = 11;
  public static final int Identificador = 26;
  public static final int Flotante = 7;
  public static final int Comillas = 3;
  public static final int Llave_c = 24;
  public static final int Llave_a = 23;
  public static final int Coma = 19;
  public static final int Numeral = 32;
  public static final int Op_relacional = 18;
  public static final int P_coma = 25;
  public static final int Tipo_de_variable = 4;
  public static final int Sino = 9;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Escribir = 30;
  public static final int Resta = 14;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Numero_flotante = 28;
  public static final int Asignacion = 17;
  public static final int Igual = 12;
  public static final int Multiplicacion = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Comillas",
  "Tipo_de_variable",
  "Entero",
  "Cadena",
  "Flotante",
  "Si",
  "Sino",
  "Mientras",
  "Para",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Asignacion",
  "Op_relacional",
  "Coma",
  "Op_booleano",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "P_coma",
  "Identificador",
  "Numero_entero",
  "Numero_flotante",
  "Leer",
  "Escribir",
  "ERROR",
  "Numeral"
  };
}

